### ISSUE TITLE
Remove/deprecate isGridCellEditable() function from SSDataGridHelper

### ISSUE THREAD

**Issue by bpangburn** [bpangburn/swingset#128]
Per @prasanthreddy-git:
Seems like we are adding a SSCellEditing object to the grid in the helper class in setActivateDeactivate function. This will effectively remove any user added SSCellEditing to the datagrid.

If a screen needs ability to allow/disallow cell editing then we can implement SSCellEditing if not it would not be needed. In the SSDataGridHelper we have an abstract method isGridCellEditable forcing users to implement it.

**Comment by bpangburn** [comment]
Whatever I did is ugly and not consistent even with SSFormViewScreenHelper. I think the goal was to encourage the developer to add any enable/disable logic in a consistent method, but I just made a mess of this code. I never took time to work with the datagrid helper beyond Example7UsingHelper and there was no enable/disable logic for that screen.

Maybe the helper could just have an abstract method such as configureSSCellEditors() called from initScreen() and then we can get rid of both:

    isGridCellEditable()
    setActivateDeactivate()


One could argue that a method like configureSSCellEditors() isn't really needed because that could be done in configureDataGrid(), but I like trying to make the methods the developer is implementing smaller and more fine-grained. I also like making them abstract so that the user has to have a bit of code to override even if it's just an empty method. If we give them an implementation then they don't have to stop and think about it.

My overall goal with the helpers was to eliminate any code that is duplicated across all grids/forms and try to force the user to implement screens consistently using abstract methods.

**Comment by bpangburn** [comment]
@prasanthreddy-git  will remove or deprecate these. I recommend adding an abstract method to SSDataGridHelper such as configureSSCellEditors() or configureCellEditing() and some sample code to the JavaDoc for that method. While this does add extra code to the implementations, it encourages the developer to put any enable/disable code in a separate method and adds consistency for other developers looking at that code later. We could give an empty implementation, but I like having the user to make that a conscious decision adding their own empty method if this logic is not needed for a screen.

**Comment by prasanthreddy-git** [comment]
Deprecated setActivateDeactivate & isGridCellEditable and also removed the call to setActivateDeactivate from initScreen. So if you have a screen using isGridCellEditable it no longer works.
Added a abstract method configureSSCellEditing where you can set SSCellEditing to the data grid.

**Comment by bpangburn** [comment]
Should be fixed in SwingSet 4.0.10
