### ISSUE TITLE
SSDataGridHelper - Unable to set the size of the datagrid when it is added to another component 

### ISSUE THREAD

**Issue by prasanthreddy-git** [bpangburn/swingset#129]
When adding a datagrid into another screen there is no ability to set the size of the grid as the scroll pane inside which it is present is not accessibl. SSDataGrid has a getComponent method that provides the scroll pane but that is not  the scroll pane used when adding the data grid to the provided parent component.

**Comment by prasanthreddy-git** [comment]
Updated code so that we are adding dataGrid.getComponent to the content pane.

**Comment by bpangburn** [comment]
Should be fixed in SwingSet 4.0.10
