### ISSUE TITLE
SSComboBox causes IllegalArgumentException

### ISSUE THREAD

**Issue by prasanthreddy-git** [bpangburn/swingset#131]
When the display field column is of type date and the value in the database is null you get the following exception.
java.lang.IllegalArgumentException: Cannot format given Object as a Date

**Comment by prasanthreddy-git** [comment]
When the date/time value from the database is null not trying to format it. Not adding anything to the display either, if not a "null" string would be appended to the display text

**Comment by bpangburn** [comment]
Should be fixed in SwingSet 4.0.10
