### ISSUE TITLE
Need ability to add an option to combo boxes when formatting is used

### ISSUE THREAD

**Issue by prasanthreddy-git** [bpangburn/swingset#139]
When formatting is used the expectation is that objects of types that correspond to underlying column data types are provided when a new option is added. But SSDBComboBox has only addOption(String, Long). If a date is passed as string to add a new option to the combobox then the formatter will throw an exception when formatting this value, stopping the combobox from working.

We probably need addOption(Object, Long) and addOption(Object, Object, Long) methods.

**Comment by prasanthreddy-git** [comment]
Thinking of changing the addOption(String, Long) to addOption(Object, Long) so that we can set the actual object (Date/Long/Float etc) or a String as done now. If an object is provided and there is a pattern then it should get formatted correctly while allowing any existing uses of passing a String.

**Comment by errael** [comment]
Taking a look at `SSDBComboBox` (all the deprecated methods and commented code make it a nightmare (but that's another issue)).

Your suggestion seems to fit. I don't remember all the compatibility concerns for existing usage... Hard to see how it would be a problem; there might be other places that need to be adjusted. I guess you'll find out :-)

I think one of the ideas going forward is to make better use of generics. Once the file is cleaned up, it should be easier to see. I think a class like `SSDBComboBoxG<...>` could be created from that file and all the signatures adjusted to use type parameters. But that is for another day.

**Comment by errael** [comment]
> If a date is passed as string to add a new option to the combobox then the formatter will throw an exception when formatting this value,

`SimpleDataFormatter` handles a string since `Date(string)` works (AFAICT). But that's beside the point, accepting an object is the right idea.

**Comment by errael** [comment]
> If an object is provided and there is a pattern then it should get formatted correctly

Patterns are deprecated now, or will be soon, assuming that PR makes it in. :-)

**Comment by bpangburn** [comment]
Fixed with PR 137: https://github.com/bpangburn/swingset/pull/137
Will be released in 4.0.10

**Comment by prasanthreddy-git** [comment]
Guess the issue was that the combo box is displaying two columns.
