### ISSUE TITLE
Component updates

### ISSUE THREAD

**Issue by prasanthreddy-git** [bpangburn/swingset#144]
Swingset components are not getting updated by the time perfromNavigationOps is called. This call is supposed to provide the screen a chance to do any operations that might be needed after a row navigation. Since the components are not updated by this time any code that relies on the value provided by the components are actually getting the prior record values rather than the new record values. 

I think the issue is use of SwingUtilities.invokeLater for updating the components. We should probably not use invokeLater for updating of components as these are not time consuming and should not impact responsiveness.

From SSCommon.java
			SwingUtilities.invokeLater(() -> {
				if (lastNotifiedChange != lastChange) {
					lastNotifiedChange = lastChange;

					updateSSComponent();
				}
			});

**Comment by bpangburn** [comment]
@prasanthreddy-git I created a ComponentUpdateFix branch for your fix(es) related to this issue. We never did have a further conversation about anything else that might need to be tweaked. I think there was some concern about whether both combo navigation and data navigator navigation. Possible that we need to look at SSSyncManager too.

**Comment by prasanthreddy-git** [comment]
Added call to activateDeactivateComponents function in performNavigationOps, performRefreshOptions, updateScreen and initScreen and calling the function using SwingUtils.invokeLater
