### ISSUE TITLE
SSComboBox/SSDBComboBox - Ability to display underlying database value when the combo doesn't have a mapping

### ISSUE THREAD

**Issue by prasanthreddy-git** [bpangburn/swingset#145]
SSComboBox/SSDBComboBox show blank combo when there is no mapping available for the database value. Would be nice if we could show the underlying database value when there is no mapping string available.

**Comment by errael** [comment]
I started with some confusion; the methods/comments refer to the displayed value as `option` and the primary key as `mapping`. In that context, I addressed displaying the `mapping` if there is no `option`. Let me know if I'm still misunderstanding.

**Comment by prasanthreddy-git** [comment]
I think that is right. When we don't have a text to display we want to display what ever is in the database itself, in which it would be the mapping based on your comments.
