### ISSUE TITLE
Extend getAllowNull() to take database column metadata into account

### ISSUE THREAD

**Issue by errael** [bpangburn/swingset#20]
The idea is to have `getAllowNull()` default to column specified metadata. This suggestion has two main parts

1. Introduce `Optional<Boolean> RowSetOps.isNullable(RowSet, Column)`
   1. If Optional isNullable().isPresent() is false then the metadata doesn't specify
   2. otherwise the optional value of isNullable reflects the metadata spec
2. modfy getAllowNull()
   1.  if setAllowNull() has been called and it has set a value, then return that.
   2. if metadata is not available then return true.
   3. otherwise if RSOps.isNullable().isPresent, then return that Boolean
   4. otherwise return true
3. setAllowNull signature is changed to take a Boolean instead of a boolean
Then setAllowNull can be set to null which mean use the metadata, null is the intial state.

This defaults to true if the metadata does not specify or if the metadata is not available.

**Comment by errael** [comment]
@bpangburn Can we get this into v4?

**Comment by bpangburn** [comment]
I like it. Go for it.

**Comment by errael** [comment]
Seems OK.
