### ISSUE TITLE
Combobox / GlazedList 'contains' anomaly

### ISSUE THREAD

**Issue by bpangburn** [bpangburn/swingset#37]
When SSComboBox or SSDBComboBox are using GlazedLists (default) there is an issue if the user types a character into the editor that does not match the first character of an item in the list. GlazedLists support is configured for substring matching (.setFilterMode(TextMatcherEditor.CONTAINS)), but there appears to be an anomaly in GlazedLists such that the first character is always checked using a "starts with" strategy.

Per @errael "It uses an array of strategies with only one element, a "startsWithMatcher". Add a second strategy, "contains", it first would try startswith, if that fails it would try contains."

The result is that if a combo contains two items {switch, knob} there will be matches if the user types "s" or "k", but not, for example, "w". If the user types "w", <backspace>, "w" the contains strategy kicks in.

This triggers unnecessary calls to setSelectedItem(null), which also attempt to update the rowset. If a component is configured with setAllowNull(false) then popup warnings appear.

Options include:
1. submitting a patch to GlazedList to modify how the matching strategies are applied
2. adding an enhancement to GlazedLists to support the STRICT and CONTAINS options together (see: https://github.com/glazedlists/glazedlists/issues/676)
3. returning with no action inside setSelectedItem() when getAllowNull()==false AND getModel().getSize() > 0 (ignoring any component update when there are no items in the list)
4. disabling listeners on the component (which trigger rowset updates, navigation) when the combo popup is visible

4 is likely a desired enhancement regardless of this Issue as it would stop unnecessary rowset updates (bound combo) and record traversals (combo navigator) when the user is typing in the editor or using the arrow keys to traverse the combo items.

**Comment by errael** [comment]
There's a draft PR, https://github.com/glazedlists/glazedlists/pull/694, to support strict+contains.

**Comment by errael** [comment]
To verify/check if glazed strict+contains fixes the issues, steps to reproduce the problems are required. This is particularly important considering #45 which is supposed to mask the problems.

**Comment by errael** [comment]
In https://github.com/bpangburn/swingset/pull/45/files#r550332940 there's

> Example 3. Type "am", into Part and we get this in the logs:

Compare to when strict+contains to understand issue.

**Comment by errael** [comment]
I hadn't noticed that this was closed, reopening. I'm still in the middle of working options 1 and 2 from the original report, https://github.com/bpangburn/swingset/issues/37#issue-774024966

In addition, this could be an umbrella issue that includes #60

**Comment by errael** [comment]
> To verify/check if glazed strict+contains fixes the issues, steps to reproduce the problems are required. This is particularly important considering #45 which is supposed to mask the problems.

If you have some time...
