### ISSUE TITLE
Consolidate Add/Remove of Component Listeners used for rowset binding

### ISSUE THREAD

**Issue by bpangburn** [bpangburn/swingset#79]
There is code in SSBaseComboBox.setSelectedMapping() that logs a warning and calls setSelectedItem(nullItem) if there is no matching item. There is a fairly common use-case where this is expected and that is where a SSDBComboBox is re-queried for every record due to a parent-child relationship. For example if we had one SSDBComboBox with companies and another one with employees, we would expected the employee combo to requery for each record where there was a change in company selected.

As soon as a navigation occurs, the component values are cleared and then the new value is loaded, but the combo has not been re-queried yet so there are no matches for setSelectedMapping() and we call setSelectedItem(nullItem). This is OK so long as the component listener used for binding is removed/disabled because the rowset will not get the null value. Later when the combo is requeried, the component will try to load the current column value from the rowset and this time setSelectedMapping() should succeed.

The "problem" is that the logger warning is scary because it indicates possible data corruption so we don't want to make the entry if the listener is off. I turned on debug level logging and expected to see the addition/removal of the listeners and I did not.

When my debugging was not as expected, I realized I was a little sloppy in how I was adding/removing the component value change listeners and was not funneling through common methods. The RowSet listeners are good, but the component value change listener implementations and listener type vary by component and should be consolidated.

One of the SS4 design goals was to funnel all RowSet listeners triggering component value changes through common methods. Same with all component value changes triggering RowSet updates. This also allows for checking that we don't accidentally create multiple change listeners for either the component or the RowSet. There can be other listeners, but for a given component binding, there should be exactly one rowset and one component listener that triggers a corresponding change in the value of the component or rowset. No duplicates. No cascading.

**Comment by bpangburn** [comment]
As a solution, I decided that each SwingSet component should NOT implement and abstract addSSComponentListener() or removeSSComponentListener(). I made add/removeSSComponentListener() and  add/removeRowSetListener() static in SSComponentInterface and have them call the appropriate SSCommon methods which are now declared as final.

Added a new abstract method to SSComponentInterface(), getSSComponentListener() which returns an EventListener.

`
	/**
	 * Return the listener that should detect a change in value for the current
	 * component.
	 * <p>
	 * Generally the developer will need to add an inner class and corresponding
	 * data member that implements the appropriate listener for the JComponent
	 * involved (e.g., ItemListener for a class extending JCheckBox, ChangeListener
	 * for a class extending JSlider, DocumentListener for a class extending
	 * JTextField, etc.).
	 * <p>
	 * If the component is JTextComponent then the implementation can add an
	 * instance variable of type SSCommon.SSCommonDocumentListener().
	 * <p>
	 * A typical implementation might look like: {@code
	 * 
	 * 	if (ssCheckBoxListener==null) {
	 * 		ssCheckBoxListener = new SSCheckBoxListener();
	 * 	}
	 * 
	 *	return ssCheckBoxListener;
	 * }
	 * 
	 * OR (for a JTextComponent): {@code
	 * 	return getSSCommon().getSSDocumentListener();
	 * }
	 * 
	 * @return change listener for the current SwingSet component to trigger RowSet update
	 */
	EventListener getSSComponentListener();
`

**Comment by bpangburn** [comment]
Note that other than the DocumentListener which can be standardized across JTextComponents, the other component-specific EventListener inner classes are still implemented in each component.

**Comment by errael** [comment]
> Note that other than the DocumentListener which can be standardized across JTextComponents, the other component-specific EventListener inner classes are still implemented in each component.

One thought, could each component could have  a trivial listener, according to type, that invokes a common someChange() method? (and this might not make sense)
