### ISSUE TITLE
Data Grid Fill Functionality

### ISSUE THREAD

**Issue by bpangburn** [bpangburn/swingset#9]
2004-06-29, Brian Pangburn: https://sourceforge.net/p/swingset/feature-requests/13/

It would be nice to be able to "fill" down or right (and maybe up or left as well) similar to Excel.

Basically you could select a start cell and a block of adjacent cells and then use <ctl-d> to fill down, <ctl-r> to fill right, etc.

Filling copies the value in the start cell to the other cells selected.

**Comment by bpangburn** [comment]
Probably need to let the developer have the option to toggle this off.

**Comment by prasanthreddy-git** [comment]
Given that this is data from a database and not a empty table, excel style fill down might be dangerous.

**Comment by bpangburn** [comment]
> Given that this is data from a database and not a empty table, excel style fill down might be dangerous.

Agreed. Was brainstorming nice to have features, but didn't think through this one. Will close.
