### ISSUE TITLE
Copy paste doesn't work in data grid with postgresql driver verison 42.2.13 and later

### ISSUE THREAD

**Issue by prasanthreddy-git** [bpangburn/swingset#90]
Copy paste into data grid fails with postgresql driver 42.2.11 and later. Seems to work file until 42.2.10.

**Comment by prasanthreddy-git** [comment]
After loading the first column data entered movetoCurrentRow is called. When entering data for the same row postgresql driver is throwing an exception "java.lang.IllegalArgumentException: Attempted to write to readonly tuple".

If we call rowset.absolute(rownumber) before updating the row postgresql doesn't through the exception. Right now we don't all the rowset.absolute if we are already on the row that needs to be updated.

**Comment by prasanthreddy-git** [comment]
https://github.com/pgjdbc/pgjdbc/issues/2194

**Comment by bpangburn** [comment]
This was an issue in the PostgreSQL JDBC driver that has since been resolved:
https://github.com/pgjdbc/pgjdbc/issues/2193
https://github.com/pgjdbc/pgjdbc/issues/2194
